routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('bookmarks');
});

Route::resource('bookmarks', 'BookmarkController');

app/Models/Bookmark.php
<?php

namespace Bookmarks\Models;

use Bookmarks\Helpers\UrlCorrector;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Laravel\Scout\Searchable;
use QL\QueryList;

class Bookmark extends Model
{
    use Searchable;

    protected $fillable = ['url', 'title', 'favicon', 'meta_description', 'meta_keywords'];

    public static function boot()
    {
        parent::boot();

        self::deleted(function ($model) {
            Storage::delete('public/' . $model->favicon);
        });
    }

    public function deletionCode()
    {
        return $this->hasOne('Bookmarks\Models\DeletionCode');
    }

    /**
     * Check existence by URL.
     *
     * @param string $url
     * @return bool
     */
    public function isExist(string $url): bool
    {
        return $this->where('url', $url)->count() > 0 ? true : false;
    }

    /**
     * Create model by Url.
     *
     * @param string $url
     */
    public function createByUrl(string $url)
    {
        $ql = QueryList::get($url);
        $hrefIco = $ql->find('link[rel*="icon"]')->href;

        $this->fill([
            'url' => $url,
            'title' => $ql->find('title')->text(),
            'favicon' => $this->getFavicon($url, $hrefIco),
            'meta_description' => $ql->find('meta[name=description]')->content,
            'meta_keywords' => $ql->find('meta[name=keywords]')->content
        ]);
        $this->save();
    }

    /**
     * @param string $url
     * @param string $hrefIco
     * @return string
     */
    protected function getFavicon(string $url, string $hrefIco)
    {
        if (!empty($hrefIco)) {
            $urlCorrector = new UrlCorrector;
            $urlCorrector->setAbsoluteComponents($url);
            $faviconUrl = $urlCorrector->relativeToAbsolute($hrefIco);

            $faviconExt = explode(".", $faviconUrl);
            $faviconExt = end($faviconExt);
            $faviconName = md5($url) . ".$faviconExt";
            Storage::put('public/favicons/' . $faviconName, file_get_contents($faviconUrl));
            return '/favicons/' . $faviconName;
        } else {
            return $hrefIco;
        }
    }
}

app/Models/DeletionCode.php
<?php

namespace Bookmarks\Models;

use Illuminate\Database\Eloquent\Model;

class DeletionCode extends Model
{
    public $timestamps = false;

    protected $fillable = ['code'];
}

app/User.php
<?php

namespace Bookmarks;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BookmarkController.php
<?php

namespace Bookmarks\Http\Controllers;

use Illuminate\Support\Facades\Hash;
use Bookmarks\Models\Bookmark;
use Bookmarks\Models\DeletionCode;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BookmarkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        if ($query = $request->input('query')) {
            $result = Bookmark::search($query)->paginate(2);

            return view('pages.search.result', [
                'searchQuery'   => $query,
                'searchResult'  => $result,
                'searchTotal'   => $result->total()
            ]);
        } else {
            $bookmarks = Bookmark::select('id', 'created_at', 'url', 'favicon', 'title')
                ->orderBy('created_at', 'desc')
                ->paginate(5);

            return view('pages.bookmarks', [
                'bookmarks' => $bookmarks
            ]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('pages.create');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'url'   => 'required|active_url',
            'pass'  => 'required'
        ]);

        $bookmark = new Bookmark();
        if ($bookmark->isExist($request->url)) {
            return response()->json([
                'message'   => 'Закладка с таким url уже существует.',
                'status'    => 'error',
                'redirect'  => ''
            ]);
        } else {
            try {
                DB::beginTransaction();
                $bookmark->createByUrl($request->url);
                $code = new DeletionCode(['code' => Hash::make($request->pass)]);
                $bookmark->deletionCode()->save($code);
                DB::commit();

                return response()->json([
                    'message'   => '',
                    'status'    => 'success',
                    'redirect'  => route('bookmarks.show', $bookmark->id)
                ]);
            } catch (\Exception $e) {
                DB::rollBack();

                return response()->json([
                    'message'   => 'Не удалось добавить закладку.',
                    'status'    => 'error',
                    'redirect'  => ''
                ]);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $bookmark = Bookmark::findOrFail($id);

        return view('pages.bookmark', [
            'bookmark' => $bookmark
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param $id
     * @return string
     */
    public function destroy(Request $request, $id)
    {
        $bookmark = Bookmark::find($id);
        $deletionCode = $bookmark->deletionCode;
        
        if (Hash::check($request->code, $deletionCode->code)) {
            try {
                DB::beginTransaction();
                $bookmark->delete();
                $deletionCode->delete();
                DB::commit();

                return response()->json([
                    'message'   => '',
                    'status'    => 'success',
                    'redirect'  => route('bookmarks.index')
                ]);
            } catch (\Exception $e) {
                DB::rollBack();

                return response()->json([
                    'message'   => 'Не удалось удалить закладку.',
                    'status'    => 'error',
                    'redirect'  => ''
                ], 500);
            }
        } else {
            return response()->json([
                'message'   => 'Введен некорректный пароль.',
                'status'    => 'error',
                'redirect'  => ''
            ]);
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace Bookmarks\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/includes/bookmarkTable.blade.php
<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">Дата добавления</th>
        <th scope="col">Favicon</th>
        <th scope="col">URL</th>
        <th scope="col">Заголовок страницы</th>
    </tr>
    </thead>
    <tbody>

    @foreach($bookmarks as $bookmark)
        <tr class='clickable-row' data-href='{{ route('bookmarks.show', ['id' => $bookmark->id]) }}'>
            <td scope="row">{{ $bookmark->created_at->format('d.m.Y') }}</td>
            <td>@if($bookmark->favicon)<img width="16px" src="{{ $bookmark->favicon }}" alt="">@endif</td>
            <td>{{ $bookmark->url }}</td>
            <td>{{ $bookmark->title }}</td>
        </tr>
    @endforeach

    </tbody>
</table>

resources/views/master.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" type="text/css" href="{{ mix('/css/app.css') }}">
    <title>{{ config('app.name') }}</title>
</head>
<body>
    <div class="container" id="app">
        @yield('content')
    </div>
    <script src="{{ mix('/js/app.js') }}"></script>
</body>
</html>

resources/views/modal/delete.blade.php
<div class="modal fade" id="deleteModalCenter" tabindex="-1" role="dialog" aria-labelledby="deleteModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalCenterTitle">Удаление закладки</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('bookmarks.destroy', $bookmark->id) }}" id="deleteBookmark">
                @method('DELETE')
                <div class="modal-body">
                    <div class="alert alert-warning" role="alert">
                        Для удаления закладки необходимо ввести пароль, который был установлен при её добавлении.
                    </div>
                    <div style="display: none" class="alert alert-danger err-msg" role="alert"></div>
                    <input required id="pass" type="password" class="form-control" placeholder="Введите пароль для удаления">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-danger">Удалить закладку</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/pages/bookmark.blade.php
@extends('master')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="pt-4">
                <div class="shadow-lg p-3 mb-5 bg-white rounded">
                    <h1>Информация о закладке</h1>
                </div>
            </div>
        </div>

        <div class="col-lg-12 pb-4">
            <a href="{{ route('bookmarks.index') }}"
               class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">
                Вернуться к списку закладок
            </a>

            <a id="js-delete"
               href="#deleteModalCenter"
               data-toggle="modal"
               class="btn btn-danger btn-sm active float-right" role="button" aria-pressed="true">
                Удалить закладку
            </a>
        </div>

        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <strong>{{ $bookmark->title ?? '' }}</strong>
                </div>
                <div class="card-body">
                    <p class="card-title">
                        @if($bookmark->favicon)
                            <img width="16px" src="{{ $bookmark->favicon }}" alt="">
                        @endif
                        <a class="pl-2" href="{{ $bookmark->url }}">{{ $bookmark->url }}</a></p>
                    @if($bookmark->meta_description)
                        <p class="card-text">{{ $bookmark->meta_description }}</p>
                    @endif
                    @if($bookmark->meta_keywords)
                        @foreach(explode(',', $bookmark->meta_keywords) as $keyword)
                            <button type="button" class="btn btn-secondary btn-sm">{{$keyword}}</button>
                        @endforeach
                    @endif
                </div>
                <div class="card-footer text-muted">
                    {{ $bookmark->created_at }}
                </div>
            </div>
        </div>
    </div>
    @include('modal.delete', ['bookmark->id' => $bookmark->id])
@endsection

resources/views/pages/bookmarks.blade.php
@extends('pages.index')

@section('bookmarks')
@if($bookmarks->count() > 0)
    <div class="col-lg-12">
        <div class="shadow-sm p-3 mb-5 bg-white rounded table-responsive">
            @include('pages.search.form')

            @include('includes.bookmarkTable')

            {{ $bookmarks->links() }}
        </div>
    </div>
@endif
@endsection

resources/views/pages/create.blade.php
@extends('master')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="pt-4">
                <div class="shadow-lg p-3 mb-5 bg-white rounded">
                    <h1>Добавление новой закладки</h1>
                </div>
            </div>
        </div>

        <div class="col-lg-12 pb-4">
            <a href="{{ route('bookmarks.index') }}"
               class="btn btn-secondary btn-sm active" role="button" aria-pressed="true">
                Вернуться к списку закладок
            </a>
        </div>

        <div class="col-lg-12">
            <div class="shadow-sm p-3 mb-5 bg-white rounded">
                <form action="{{ route('bookmarks.store') }}" method="post" id="createBookmark">
                    <div class="form-group row">
                        <label for="url" class="col-sm-2 col-form-label">URL закладки</label>
                        <div class="col-sm-10">
                            <input required type="text" class="form-control" id="url" placeholder="URL страницы">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="pass" class="col-sm-2 col-form-label">Пароль для удаления</label>
                        <div class="col-sm-10">
                            <input required type="password" class="form-control" id="pass" placeholder="Пароль удаления">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Добавить закладку</button>
                </form>

                <div class="pt-4">
                    <div class="alert alert-danger err-msg" style="display: none" role="alert"></div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/index.blade.php
@extends('master')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="pt-4">
                <div class="shadow-lg p-3 mb-5 bg-white rounded">
                    <h1>Список всех закладок</h1>
                </div>
            </div>
        </div>

        <div class="col-lg-12 pb-4">
            <a href="{{ route('bookmarks.create') }}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">
                Добавить новую закладку
            </a>
        </div>

        @yield('bookmarks')
    </div>
@endsection

resources/views/pages/search/form.blade.php
<div class="pt-2 pb-4">
    <form method="get">
        <div class="form-row">
            <div class="col-lg-12">
                <label class="sr-only" for="search">Search</label>
                <input required type="text"
                       class="form-control mb-2"
                       id="search" name="query"
                       placeholder="Поиск по закладкам"
                       value="{{ $searchQuery ?? '' }}">
            </div>
            <div class="col-lg-12">
                <input class="btn btn-primary" type="submit" value="Поиск">
                @if(isset($searchQuery))
                    <a class="btn btn-primary btn-outline-danger" href="{{ route('bookmarks.index') }}">сбросить</a>
                @endif
            </div>
        </div>
    </form>
</div>

resources/views/pages/search/result.blade.php
@extends('pages.index')

@section('bookmarks')
    <div class="col-lg-12">
        <div class="shadow-sm p-3 mb-5 bg-white rounded table-responsive">
            @include('pages.search.form', ['search' => $searchQuery])

            @if($searchResult->count() > 0)
                <div class="alert alert-secondary" role="alert">
                    По запросу "<strong>{{ $searchQuery }}</strong>" найдено {{ $searchResult->total() }}
                    {{ \Illuminate\Support\Facades\Lang::choice('результат|результата|результов',
                    $searchResult->total(), [], 'ru') }}.
                </div>

                @include('includes.bookmarkTable', ['bookmarks' => $searchResult])
                {{ $searchResult->links() }}
            @else
                <div class="alert alert-secondary" role="alert">
                    По запросу "<strong>{{ $searchQuery }}</strong>" ничего не найдено.
                </div>
            @endif
        </div>
    </div>
@endsection